server:
  host: "localhost"
  port: 8080
  log_level: "info"

database:
  type: "postgres"
  host: "localhost"
  port: 5432
  username: "your_username"
  password: "your_password"
  dbname: "htl_defense"

api:
  version: "v1"
  base_path: "/api"

security:
  jwt_secret: "your_jwt_secret"
  token_expiration: "1h"